services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_NAME=mizzoumarketplacedb
      - DB_USER=truman
      - DB_PASSWORD=mizzoutiger
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=truman
      - POSTGRES_PASSWORD=mizzoutiger
      - POSTGRES_DB=mizzoumarketplacedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: